# version: '3.8'

# services:
#   backend:
#     build:
#       context: ./server
#       dockerfile: Dockerfile
#     container_name: backend
#     restart: always
#     ports:
#       - "3000:3000"
#     env_file:
#       - ./server/.env.production
#     networks:
#       - app-network

#   frontend:
#     build:
#       context: ./client
#       dockerfile: Dockerfile
#     container_name: frontend
#     restart: always
#     ports:
#       - "80:80"
#     depends_on:
#       - backend
#     networks:
#       - app-network

# networks:
#   app-network:
#     driver: bridge

version: '3.8'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env.production
    volumes:
      - /etc/letsencrypt/live/thunder-store.ru:/etc/letsencrypt/live/thunder-store.ru
      - /etc/letsencrypt/archive/thunder-store.ru:/etc/letsencrypt/archive/thunder-store.ru
    networks:
      - app-network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    depends_on:
      - backend
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
