version: "3"
services:
  backend:
    build:
      context: ./server
      args:
        SERVER_URL: ${SERVER_URL}
        CORS_ORIGIN: ${CORS_ORIGIN}
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    environment:
      - SERVER_URL=${SERVER_URL}
      - CORS_ORIGIN=${CORS_ORIGIN}

  frontend:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - backend
